// src/app/layout.jsx
import { Inter } from "next/font/google"; // Or your chosen font
import "./globals.css"; // Your global styles
import MainLayoutClient from "@/Components/layout/MainLayoutClient"; // Import the client wrapper

import LockScreenWrapper from "@/components/auth/LockScreenWrapper";

const inter = Inter({ subsets: ["latin"] });

// Metadata can still be exported like this in JS
export const metadata = {
  title: "My Dashboard App", // Example Title
  description: "Generated by create next app",
};

// This is a Server Component (no 'use client')
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Render the client component which handles Navbar, Sheet, and state */}
        <LockScreenWrapper>
          <MainLayoutClient>
            {children} {/* Pass the page content down */}
          </MainLayoutClient>
        </LockScreenWrapper>
      </body>
    </html>
  );
}
